server:
  port: 8080

spring:
  application:
    name: store-saas-backend
  profiles:
    active: dev
  # 文件上传配置
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB

# MyBatis-Plus 配置
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
  global-config:
    db-config:
      logic-delete-field: deleted
      logic-delete-value: 1
      logic-not-delete-value: 0

# Sa-Token 配置
sa-token:
  token-name: Authorization
  token-prefix: Bearer
  timeout: 2592000
  active-timeout: 7200
  is-concurrent: true
  is-share: false
  token-style: uuid
  is-log: true

# Swagger UI 配置
springdoc:
  swagger-ui:
    path: /swagger-ui.html

# Apollo 配置中心引导配置
apollo:
  meta: ${APOLLO_META:http://192.168.85.202:8080}
  cacheDir: ${APOLLO_CACHE_DIR:./.apollo-cache}
  bootstrap:
    enabled: ${APOLLO_BOOTSTRAP_ENABLED:true}
    namespaces: application
    eagerLoad:
      enabled: true
